//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITIES
    {
        public long Id { get; set; }
        public long User_Id { get; set; }
        public Nullable<int> Subject_Id { get; set; }
        public string Subject_Type { get; set; }
        public System.DateTime Createed_At { get; set; }
        public System.DateTime Updated_At { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
