//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURIER_AREA_CHARGES
    {
        public COURIER_AREA_CHARGES()
        {
            this.COURIER_DETAIL = new HashSet<COURIER_DETAIL>();
        }
    
        public int Id { get; set; }
        public string Area { get; set; }
        public string State_Id { get; set; }
        public Nullable<int> Courier_Id { get; set; }
        public Nullable<decimal> Charger { get; set; }
    
        public virtual STATE STATE { get; set; }
        public virtual ICollection<COURIER_DETAIL> COURIER_DETAIL { get; set; }
    }
}
