//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURIER_DETAIL
    {
        public int Id { get; set; }
        public string State_Id { get; set; }
        public int Area_Id { get; set; }
        public int Courier_Id { get; set; }
        public int Charge_Id { get; set; }
    
        public virtual COURIER_AREA_CHARGES COURIER_AREA_CHARGES { get; set; }
        public virtual COURIER_CHARGES COURIER_CHARGES { get; set; }
        public virtual COURIER_SERVICE COURIER_SERVICE { get; set; }
        public virtual STATE STATE { get; set; }
    }
}
