//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_REVIEW
    {
        public int Customer_Review_Id { get; set; }
        public long Product_Id { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Email { get; set; }
        public string Customer_Review_Subject { get; set; }
        public int Customer_Rating { get; set; }
        public string Customer_Review1 { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
