//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_ORDER
    {
        public long Customer_Order_Id { get; set; }
        public long Customer_Id { get; set; }
        public string Customer_Order_Number { get; set; }
        public Nullable<long> Delivery_Service_Id { get; set; }
        public string Customer_Delivery_Address { get; set; }
        public string Cart_Hash { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Created_At { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual DELIVERY_SERVICE DELIVERY_SERVICE { get; set; }
        public virtual PAYMENT_PAYSTACK PAYMENT_PAYSTACK { get; set; }
    }
}
