//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY_ADDRESS
    {
        public long Delivery_Address_Id { get; set; }
        public int Delivery_Service_Id { get; set; }
        public int Delivery_Status_Id { get; set; }
        public string Cart_Hash { get; set; }
        public string Address { get; set; }
        public string Delivery_State_Id { get; set; }
        public long Person_Id { get; set; }
        public System.DateTime Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Delivered { get; set; }
        public int Delivery_Option { get; set; }
    
        public virtual DELIVERY_SERVICE DELIVERY_SERVICE { get; set; }
        public virtual DELIVERY_STATUS DELIVERY_STATUS { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
