//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY_SERVICE
    {
        public DELIVERY_SERVICE()
        {
            this.DELIVERY_ADDRESS = new HashSet<DELIVERY_ADDRESS>();
        }
    
        public int Delivery_Service_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public bool Activated { get; set; }
    
        public virtual ICollection<DELIVERY_ADDRESS> DELIVERY_ADDRESS { get; set; }
    }
}
