//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOME_PAGE_SLIDER
    {
        public int Home_Page_Slider_Id { get; set; }
        public string Image_Url { get; set; }
        public bool Activated { get; set; }
    }
}
