//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_MODE
    {
        public PAYMENT_MODE()
        {
            this.PAYMENT = new HashSet<PAYMENT>();
        }
    
        public int Payment_Mode_Id { get; set; }
        public string Payment_Mode_Name { get; set; }
        public string Payment_Mode_Description { get; set; }
    
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
    }
}
