//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_PAYSTACK
    {
        public long Payment_Id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string currency { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public string status { get; set; }
        public string reference { get; set; }
        public string domain { get; set; }
        public string gateway_response { get; set; }
        public string message { get; set; }
        public string channel { get; set; }
        public string ip_address { get; set; }
        public string fees { get; set; }
        public string last4 { get; set; }
        public string exp_month { get; set; }
        public string exp_year { get; set; }
        public string card_type { get; set; }
        public string bank { get; set; }
        public string country_code { get; set; }
        public string brand { get; set; }
        public Nullable<bool> reusable { get; set; }
        public string signature { get; set; }
        public string authorization_url { get; set; }
        public string access_code { get; set; }
    
        public virtual PAYMENT PAYMENT { get; set; }
    }
}
