//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public PERSON()
        {
            this.DELIVERY_ADDRESS = new HashSet<DELIVERY_ADDRESS>();
            this.PAYMENT = new HashSet<PAYMENT>();
            this.STORE_SETUP = new HashSet<STORE_SETUP>();
        }
    
        public long Person_Id { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string OtherName { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public string Address { get; set; }
        public Nullable<int> Country_Id { get; set; }
        public string State_Id { get; set; }
        public Nullable<System.DateTime> Date_Registered { get; set; }
        public int User_Id { get; set; }
        public string Uuid { get; set; }
    
        public virtual ICollection<DELIVERY_ADDRESS> DELIVERY_ADDRESS { get; set; }
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
        public virtual USER USER { get; set; }
        public virtual ICollection<STORE_SETUP> STORE_SETUP { get; set; }
    }
}
