//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.CUSTOMER_REVIEW = new HashSet<CUSTOMER_REVIEW>();
            this.CUSTOMER_VISIT = new HashSet<CUSTOMER_VISIT>();
            this.INVENTORY = new HashSet<INVENTORY>();
            this.PRODUCT_IMAGE_GALLARY = new HashSet<PRODUCT_IMAGE_GALLARY>();
            this.PRODUCT_ORDER_LOG = new HashSet<PRODUCT_ORDER_LOG>();
            this.PRODUCT_SUPPLY_LOG = new HashSet<PRODUCT_SUPPLY_LOG>();
            this.PRODUCT_VARIANT = new HashSet<PRODUCT_VARIANT>();
            this.SALES_LOG = new HashSet<SALES_LOG>();
        }
    
        public long Id { get; set; }
        public string Slug { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public bool Shipping { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public bool Can_Be_Delivered { get; set; }
        public int Product_Type_Id { get; set; }
        public int Reorder_Level { get; set; }
        public Nullable<int> Visits { get; set; }
        public string Image_Url { get; set; }
        public string sku { get; set; }
        public long Brand_Id { get; set; }
        public int Unit_Id { get; set; }
        public bool Active { get; set; }
        public string Additional_Information { get; set; }
    
        public virtual BRAND BRAND { get; set; }
        public virtual ICollection<CUSTOMER_REVIEW> CUSTOMER_REVIEW { get; set; }
        public virtual ICollection<CUSTOMER_VISIT> CUSTOMER_VISIT { get; set; }
        public virtual ICollection<INVENTORY> INVENTORY { get; set; }
        public virtual ICollection<PRODUCT_IMAGE_GALLARY> PRODUCT_IMAGE_GALLARY { get; set; }
        public virtual ICollection<PRODUCT_ORDER_LOG> PRODUCT_ORDER_LOG { get; set; }
        public virtual PRODUCT_TYPE PRODUCT_TYPE { get; set; }
        public virtual ICollection<PRODUCT_SUPPLY_LOG> PRODUCT_SUPPLY_LOG { get; set; }
        public virtual UNIT UNIT { get; set; }
        public virtual ICollection<PRODUCT_VARIANT> PRODUCT_VARIANT { get; set; }
        public virtual ICollection<SALES_LOG> SALES_LOG { get; set; }
    }
}
