//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_VARIANT_OPTIONS
    {
        public PRODUCT_VARIANT_OPTIONS()
        {
            this.INVENTORY = new HashSet<INVENTORY>();
            this.SALES_LOG = new HashSet<SALES_LOG>();
        }
    
        public long Product_Option_Id { get; set; }
        public string Product_Option_Name { get; set; }
        public int Product_Variant_Id { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Image_Url { get; set; }
    
        public virtual ICollection<INVENTORY> INVENTORY { get; set; }
        public virtual PRODUCT_VARIANT PRODUCT_VARIANT { get; set; }
        public virtual ICollection<SALES_LOG> SALES_LOG { get; set; }
    }
}
