//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_TYPE
    {
        public PRODUCT_TYPE()
        {
            this.PRODUCT = new HashSet<PRODUCT>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public int Category_Id { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual ICollection<PRODUCT> PRODUCT { get; set; }
    }
}
