//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_IMAGE_GALLARY
    {
        public int Product_Image_Gallary_Id { get; set; }
        public long Product_Id { get; set; }
        public string Image_Url { get; set; }
        public Nullable<bool> Activated { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
