//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_VARIANT
    {
        public PRODUCT_VARIANT()
        {
            this.PRODUCT_VARIANT_OPTIONS = new HashSet<PRODUCT_VARIANT_OPTIONS>();
        }
    
        public int Product_Variant_Id { get; set; }
        public long Product_Id { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Key_1 { get; set; }
        public string Value_1 { get; set; }
        public string Key_2 { get; set; }
        public string Value_2 { get; set; }
        public string Key_3 { get; set; }
        public string Value_3 { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual ICollection<PRODUCT_VARIANT_OPTIONS> PRODUCT_VARIANT_OPTIONS { get; set; }
    }
}
