//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REORDER_NOTIFICATION
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public bool Status { get; set; }
        public System.DateTime DateTime { get; set; }
        public int NotificationType { get; set; }
        public string Order_Number { get; set; }
    }
}
