//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_LOG
    {
        public long Id { get; set; }
        public string Cart_Hash { get; set; }
        public long Product_Id { get; set; }
        public Nullable<long> Product_Variant_Option_Id { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> discount { get; set; }
        public decimal Unit_Price { get; set; }
        public decimal Amount { get; set; }
        public int User_Id { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Date_Ordered { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PRODUCT_VARIANT_OPTIONS PRODUCT_VARIANT_OPTIONS { get; set; }
        public virtual USER USER { get; set; }
    }
}
