//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_LOGS
    {
        public long Id { get; set; }
        public string Cart_Hash { get; set; }
        public long Product_Id { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> discount { get; set; }
        public decimal Unit_Price { get; set; }
        public decimal Amount { get; set; }
        public long User_Id { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual USER USER { get; set; }
    }
}
