//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATE
    {
        public STATE()
        {
            this.COURIER_AREA_CHARGES = new HashSet<COURIER_AREA_CHARGES>();
            this.COURIER_DETAIL = new HashSet<COURIER_DETAIL>();
        }
    
        public string State_Id { get; set; }
        public string State_Name { get; set; }
        public int Nationality_Id { get; set; }
    
        public virtual ICollection<COURIER_AREA_CHARGES> COURIER_AREA_CHARGES { get; set; }
        public virtual ICollection<COURIER_DETAIL> COURIER_DETAIL { get; set; }
        public virtual NATIONALITY NATIONALITY { get; set; }
    }
}
