//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE_SETUP
    {
        public long Store_Setup_Id { get; set; }
        public long Person_Id { get; set; }
        public string Shop_Name { get; set; }
        public string Store_ProductType { get; set; }
        public string BusinessName { get; set; }
        public string BusinessRCNo { get; set; }
        public string BusinessPhone { get; set; }
        public string BusinessEmail { get; set; }
        public string StoreLogoUrl { get; set; }
        public string About_Us { get; set; }
        public string Store_Address { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
