//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDOR
    {
        public VENDOR()
        {
            this.PRODUCT_ORDER_LOG = new HashSet<PRODUCT_ORDER_LOG>();
            this.PRODUCT_SUPPLY_LOG = new HashSet<PRODUCT_SUPPLY_LOG>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone_Number { get; set; }
        public string Email { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<PRODUCT_ORDER_LOG> PRODUCT_ORDER_LOG { get; set; }
        public virtual ICollection<PRODUCT_SUPPLY_LOG> PRODUCT_SUPPLY_LOG { get; set; }
    }
}
