//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_SN.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SALES_PAYMENT
    {
        public string Name { get; set; }
        public long Payment_Id { get; set; }
        public string Invoice_Number { get; set; }
        public long Person_Id { get; set; }
        public int Payment_Mode_Id { get; set; }
        public string Payment_Mode_Name { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
    }
}
